Document: opencc4php
Title: Debian opencc4php Manual
Author: <insert document author here>
Abstract: This manual describes what opencc4php is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/opencc4php/opencc4php.sgml.gz

Format: postscript
Files: /usr/share/doc/opencc4php/opencc4php.ps.gz

Format: text
Files: /usr/share/doc/opencc4php/opencc4php.text.gz

Format: HTML
Index: /usr/share/doc/opencc4php/html/index.html
Files: /usr/share/doc/opencc4php/html/*.html
